# VERBOSITY
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0
## Making sure electroluminescence is turned on
## Nexus Physics List
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  false


/nexus/random_seed 10000000

#GEOMETRY
/Geometry/CRAB/gas_pressure 9.7 bar
/Geometry/CRAB/scinYield 0 1/MeV
/Geometry/CRAB/chamber_diam  15. cm
/Geometry/CRAB/chamber_length 43.18 cm
/Geometry/CRAB/chamber_thickn 2. mm
#/Geometry/CRAB/SourcePosition -4.5 -4.5 -4.5 cm
#/Geometry/CRAB/SourcePosition -3 0 -5 cm
/Geometry/CRAB/SourcePosition -1.6 0 -5 cm
/Actions/CRABAnalysisSteppingAction/FileSave true
/Actions/CRABAnalysisSteppingAction/FileName test.txt


#Active
/Geometry/CRAB/Active_diam 8.5 cm
/Geometry/CRAB/Active_length 42 cm

## Source Enclosures
/Geometry/CRAB/HideSource false
/Geometry/CRAB/HideCollimator false

# GENERATOR
/Generator/CrabSourceGenerator/region OUTER_SURFACE
#Pb_210
/Generator/CrabSourceGenerator/atomic_number 82
/Generator/CrabSourceGenerator/mass_number 210


/Generator/CrabSourceGenerator/decay_rate 100000 nCi
#/Generator/CrabSourceGenerator/event_window 13
#works only if event_window is zero
#/Generator/CrabSourceGenerator/NDecays 1

#Actions
#/Actions/DefaultEventAction/energy_threshold 100 eV
#/Actions/DefaultEventAction/max_energy 1.00 GeV
#/Actions/DefaultEventAction/min_energy 100 eV

# PERSISTENCY
/nexus/persistency/eventType background
/nexus/persistency/outputFile /media/ilker/Ilker/SimResults/Jan1_2023/pb210t
#/nexus/persistency/outputFile kkv121
