

# VERBOSITY
/run/verbose 1
/event/verbose 1
/tracking/verbose 1
/process/em/verbose 1
## Making sure electroluminescence is turned on


# GENERATION
/Generator/SingleParticle/region FIELDCAGE
/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 10 eV
/Generator/SingleParticle/max_energy 10 eV
#/Generator/SingleParticle/min_costheta -1
#/Generator/SingleParticle/max_costheta -1
/Generator/SingleParticle/min_costheta 0
/Generator/SingleParticle/max_costheta 0
/Generator/SingleParticle/min_phi 0
/Generator/SingleParticle/max_phi 0

/Actions/CRABAnalysisSteppingAction/FileSave true

## Nexus Physics List
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

#GEOMETRY
/Geometry/CRAB/gas_pressure 10. bar
/Geometry/CRAB/scinYield 1 1/MeV
/Geometry/CRAB/chamber_diam  15. cm
/Geometry/CRAB/chamber_length 43.18 cm
/Geometry/CRAB/chamber_thickn 2. mm
/Geometry/CRAB/SourcePosition -1.6 0 -5 cm
#/Geometry/CRAB/SourcePosition 0 0 0 cm
/Geometry/CRAB/ElecLifTime 100 ms
/Geometry/CRAB/ELGap 7 mm



#Active
/Geometry/CRAB/Active_diam 8.5 cm
/Geometry/CRAB/Active_length 42 cm

#SourceEncloser
/Geometry/CRAB/SourceEn_diam 10 mm
/Geometry/CRAB/SourceEn_holedi 5 mm
/Geometry/CRAB/SourceEn_offset 5.7 cm



# PERSISTENCY
/nexus/persistency/eventType background
/nexus/persistency/outputFile test2
#/run/printProgress 100
