# VERBOSITY
/run/verbose 1
/event/verbose 1
/tracking/verbose 1
/process/em/verbose 1

#GEOMETRY
/Geometry/CRAB/gas_pressure 10. bar
/Geometry/CRAB/chamber_diam  15. cm
/Geometry/CRAB/chamber_length 47.84 cm
/Geometry/CRAB/chamber_thickn 2. mm
#/Geometry/CRAB/SourcePosition -4.5 -4.5 -4.5 cm
/Geometry/CRAB/SourcePosition -5.4 0 0 cm
#/Geometry/CRAB/SourcePosition 0 0 0 cm

#Active
/Geometry/CRAB/Active_diam 8.5 cm
/Geometry/CRAB/Active_length 45 cm

#SourceEncloser
/Geometry/CRAB/SourceEn_diam 10 mm
/Geometry/CRAB/SourceEn_holedi 5 mm
/Geometry/CRAB/SourceEn_offset 5.7 cm



# GENERATOR
/Generator/CrabSourceGenerator/region GAS
#Sr90
/Generator/CrabSourceGenerator/atomic_number 38
/Generator/CrabSourceGenerator/mass_number 90


/Generator/CrabSourceGenerator/decay_rate 100000 nCi
#/Generator/CrabSourceGenerator/event_window 13
#works only if event_window is zero
#/Generator/CrabSourceGenerator/NDecays 1

#Actions
#/Actions/DefaultEventAction/energy_threshold 100 eV
/Actions/DefaultEventAction/max_energy 1.00 GeV
/Actions/DefaultEventAction/min_energy 100 eV
# PERSISTENCY
/nexus/persistency/eventType background
/nexus/persistency/outputFile /home/argon/Projects/Ilker/NewNexus/output/Sr90Encl_1mm_5_7_offset_nov2_100kv2
#/run/printProgress 100
