# VERBOSITY
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0
## Making sure electroluminescence is turned on
## Nexus Physics List
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false


/nexus/random_seed 10000000

#GEOMETRY
/Geometry/CRAB/gas_pressure 9.7 bar
#/Geometry/CRAB/scinYield 10 1/MeV
/Geometry/CRAB/chamber_diam  15. cm
/Geometry/CRAB/chamber_length 43.18 cm
/Geometry/CRAB/chamber_thickn 2. mm
#/Geometry/CRAB/SourcePosition -4.5 -4.5 -4.5 cm
#/Geometry/CRAB/SourcePosition -3 0 -5 cm
#/Geometry/CRAB/SourcePosition 0 0 0 cm
/Actions/CRABAnalysisSteppingAction/FileSave true
/Actions/CRABAnalysisSteppingAction/FileName test.txt


#Active
/Geometry/CRAB/Active_diam 8.5 cm
/Geometry/CRAB/Active_length 42 cm

#SourceEncloser
/Geometry/CRAB/SourceEn_diam 10 mm
/Geometry/CRAB/SourceEn_holedi 5 mm
/Geometry/CRAB/SourceEn_offset 5.7 cm

# GENERATOR
/Generator/CrabSourceGenerator/region FIELDCAGE
#Pb_210
/Generator/CrabSourceGenerator/atomic_number 82
/Generator/CrabSourceGenerator/mass_number 210


/Generator/CrabSourceGenerator/decay_rate 100000 nCi
#/Generator/CrabSourceGenerator/event_window 13
#works only if event_window is zero
#/Generator/CrabSourceGenerator/NDecays 1

#Actions
#/Actions/DefaultEventAction/energy_threshold 100 eV
#/Actions/DefaultEventAction/max_energy 1.00 GeV
#/Actions/DefaultEventAction/min_energy 100 eV

# PERSISTENCY
/nexus/persistency/eventType background
#/nexus/persistency/outputFile /media/ilker/Ilker/CRAB/Simulation/For_Nick/WithNicksYieldv2
/nexus/persistency/outputFile kkv121
