## ----------------------------------------------------------------------------
## nexus | DEMOPP_fullKr.config.mac
##
## Configuration macro to simulate Kr-83 decays in the DEMO++ geometry
## with generation and transportation of optical photons.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

# VERBOSITY
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0


# GEOMETRY
/Geometry/NextDemo/config run5
/Geometry/NextDemo/elfield true
/Geometry/NextDemo/pressure 10 bar
/Geometry/NextDemo/max_step_size 1. mm
/Geometry/NextDemo/EL_field_intensity 9 kV/cm
/Geometry/NextDemo/field_cage_vis true
/Geometry/NextDemo/max_step_size 1. mm
/Geometry/PmtR11410/time_binning 100. nanosecond
#/Geometry/SiPMSensl/time_binning 1. microsecond

/process/optical/processActivation Cerenkov false


# GENERATION
/Generator/SingleParticle/region  ACTIVE
/Generator/SingleParticle/particle  alpha
/Generator/SingleParticle/min_energy 101 eV
/Generator/SingleParticle/max_energy 101 eV



# PERSISTENCY
/nexus/persistency/outputFile out_Kr83.sim

/nexus/random_seed 14562
