# VERBOSITY
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

# GENERATION
/Generator/SingleParticle/region AD_HOC
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 100 keV
/Generator/SingleParticle/max_energy 500 keV



##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 100 keV
/Actions/DefaultEventAction/max_energy 500 keV

## Nexus Physics List
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false

#GEOMETRY
/Geometry/ATPC/gas_pressure 1. bar
/Geometry/ATPC/cube_size  6 m
/Geometry/ATPC/chamber_thickn 5 cm
/Geometry/ATPC/max_step_size 10 mm


# PERSISTENCY
#/nexus/persistency/eventType background
/nexus/persistency/output_file ATPC_eminus_0.1mmstep
