# VERBOSITY
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

# GENERATION
/Generator/SingleParticle/region ACTIVE
/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy 2.6 MeV
/Generator/SingleParticle/max_energy 2.6 MeV

##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 2.3 MeV
/Actions/DefaultEventAction/max_energy 2.6 MeV

## Nexus Physics List
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false

#GEOMETRY
/Geometry/ATPC/gas_pressure 1. bar
/Geometry/ATPC/cube_size  6 m
/Geometry/ATPC/chamber_thickn 5 cm

# PERSISTENCY
#/nexus/persistency/eventType background
/nexus/persistency/output_file ATPC_gamma
