## ----------------------------------------------------------------------------
## nexus | NEXT100.config.mac
##
## Configuration macro to simulate Bi-214 radioactive decays from thethe
## copper plate of the tracking plane in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
#/Geometry/Next100/elfield false
#/Geometry/Next100/max_step_size 1. mm

##### GENERATOR #####
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 40. keV
/Generator/SingleParticle/min_energy 40. keV
/Generator/SingleParticle/region CENTER

##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 0.6 keV
/Actions/DefaultEventAction/max_energy 2.55 MeV

##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false
/PhysicsList/Nexus/fastsim true

##### PERSISTENCY #####
/nexus/persistency/output_file CRAB.next
## eventType options: bb0nu, bb2nu, background
/nexus/persistency/event_type background
