## ----------------------------------------------------------------------------
## nexus | KingCRAB_PhotonGen.config.mac
##
## Configuration macro to generate photons in KingCRAB
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

# VERBOSITY
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

# GENERATION
/Generator/ScintGenerator/region AD_HOC
/Generator/ScintGenerator/region AD_HOC
/Geometry/KingCRAB/specific_vertex 0. 0. 0. mm
/Generator/ScintGenerator/nphotons 2000000
#/Generator/ScintGenerator/nphotons 40000

## Nexus Physics List
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false

#GEOMETRY
/Geometry/KingCRAB/gas_pressure 5. bar
/Geometry/KingCRAB/max_step_size 1 mm

# PERSISTENCY
/nexus/random_seed            9
/nexus/persistency/start_id   0
/nexus/persistency/output_file KingCRAB_PhotonGen
