## ----------------------------------------------------------------------------
## nexus | KingCRAB_AlphaGen.init.mac
##
## Initialization macro to generate alphas in KingCRAB
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------


/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics

/nexus/RegisterGeometry KingCRAB

/nexus/RegisterGenerator SingleParticleGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterTrackingAction OpticalTrackingAction

/nexus/RegisterMacro macros/KingCRAB_AlphaGen.config.mac
