## ----------------------------------------------------------------------------
## nexus | NEXT100.config.mac
##
## Configuration macro to simulate Bi-214 radioactive decays from the
## copper plate of the tracking plane in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/elfield true
/Geometry/Next100/max_step_size 0.1 mm
/Geometry/Next100/pressure 5 bar
/Geometry/Next100/EL_field 10 kilovolt/cm
/Geometry/Next100/drift_transv_diff 1.44 mm/sqrt(cm)
/Geometry/Next100/drift_long_diff 0.408 mm/sqrt(cm)

/Geometry/PmtR11410/time_binning 25. nanosecond
/Geometry/Next100/sipm_time_binning  1. microsecond

##### GENERATOR #####
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 2.5 MeV
/Generator/SingleParticle/max_energy 2.5 MeV
/Generator/SingleParticle/region CENTER

#/Generator/Decay0Interface/region CENTER
#/Generator/Decay0Interface/Xe136DecayMode 1
#/Generator/Decay0Interface/Ba136FinalState 0

##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 10.0 keV
/Actions/DefaultEventAction/max_energy 2.55 MeV

##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false
/PhysicsList/Nexus/fastsim true
/PhysicsList/Nexus/nest true

##### PERSISTENCY #####
/nexus/persistency/output_file Next100.next
## eventType options: bb0nu, bb2nu, background
/nexus/persistency/event_type background
/nexus/random_seed 4456
