## ----------------------------------------------------------------------------
## nexus | NEXT100_Ar_alpha_full.config.mac
##
## Initialization macro to alpha particle decays in the active
## volume of the NEXT-100 detector during the low pressure run.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/elfield true
/Geometry/Next100/EL_field 7.5 kV/cm
/Geometry/Next100/max_step_size 1. mm
/Geometry/Next100/pressure 4.0 bar
/Geometry/Next100/gas depletedXe
/Geometry/PmtR11410/time_binning 25. nanosecond
/Geometry/Next100/sipm_time_binning  1. microsecond

/Geometry/Next100/drift_v   0.88 mm/microsecond
/Geometry/Next100/EL_drift_v 4.21 mm/microsecond

/Geometry/Next100/drift_transv_diff 1.56 mm/sqrt(cm)
/Geometry/Next100/drift_long_diff 0.55 mm/sqrt(cm)

/Geometry/Next100/ELtransv_diff 0.39 mm/sqrt(cm)
/Geometry/Next100/ELlong_diff 0.25 mm/sqrt(cm)

/Geometry/Next100/e_lifetime         65   ms

# includes 0.75 for EL emperical gain eqn, and realistic mesh scaling
/Geometry/Next100/el_scale 0.65 

##### GENERATOR #####
/Generator/SingleParticle/particle alpha

# For N100 use 5.6 MeV here
/Generator/SingleParticle/min_energy 5.6 MeV
/Generator/SingleParticle/max_energy 5.6 MeV
/Generator/SingleParticle/region AD_HOC
/Geometry/Next100/specific_vertex  0. 0. 630. mm


##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 20 keV
/Actions/DefaultEventAction/max_energy 6 MeV

##### PHYSICS #####
## Full simulation
/PhysicsList/Nexus/clustering          true
/PhysicsList/Nexus/drift               true
/PhysicsList/Nexus/electroluminescence true

##### PERSISTENCY #####
/nexus/persistency/output_file NEXT100_Xe_single_full

/nexus/random_seed             100
/nexus/persistency/start_id    100

## eventType options: bb0nu, bb2nu, background
/nexus/persistency/event_type background

/process/optical/processActivation Cerenkov false
