## ----------------------------------------------------------------------------
## nexus | NEXT100_Degrad.config.mac
##
## Configuration macro to simulate decays of the Th calibration source
## from one of the vessel ports in the NEXT-100 detector. Using GS Model
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/pressure 5 bar
/Geometry/Next100/elfield false
/Geometry/Next100/max_step_size 1. mm
/Geometry/Next100/th_source new_source 
/Geometry/Next100/gas depletedXe

##### GENERATOR #####
/Generator/IonGenerator/atomic_number 81
/Generator/IonGenerator/mass_number 208
/Generator/IonGenerator/region PORT_1a

/Actions/DefaultEventAction/min_energy 1.5 MeV
/Actions/DefaultEventAction/max_energy 2.8 MeV

##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false
/PhysicsList/Nexus/fastsim true
/PhysicsList/Nexus/nest false

##### PERSISTENCY #####
/nexus/persistency/output_file Next100_Tl208_Port1a_Degrad
/nexus/random_seed            9800
/nexus/persistency/start_id   9800
